### ISSUE TITLE
Error in Token.create Function: Unsupported Operation During Script Execution

### ISSUE THREAD

**Issue by shubhamanandspeqto** [wen-moon-ser/moonshot-sdk-evm#11]
I am encountering an issue when running a script utilizing the Moonshot SDK. Specifically, the Token.create function fails with the following error:
Error creating token: Error: contract runner does not support calling (operation="call", code=UNSUPPORTED_OPERATION, version=6.13.4)
    at makeError (/path/to/node_modules/ethers/lib.commonjs/utils/errors.js:129:21)
    at assert (/path/to/node_modules/ethers/lib.commonjs/utils/errors.js:149:15)
    at staticCallResult (/path/to/node_modules/ethers/lib.commonjs/contract/contract.js:241:31)
    at staticCall (/path/to/node_modules/ethers/lib.commonjs/contract/contract.js:219:30)
    at Proxy.curveType (/path/to/node_modules/ethers/lib.commonjs/contract/contract.js:259:26)
    at Token.create (/path/to/node_modules/@wen-moon-ser/moonshot-sdk-evm/dist/domain/token/Token.js:18:51)

AND MY SCRIPT CODE IS :
// @ts-nocheck
const { ethers } = require('ethers');
const { Web3 } = require('web3');
const erc20Abi = require("./erc20Abi.json")
const { Moonshot, Token, FixedSide, Environment } = require('@wen-moon-ser/moonshot-sdk-evm');

const buyTx = async () => {
    const rpcUrl = 'https://base-sepolia.g.alchemy.com/v2/YOUR_API_KEY';
    const web3 = new Web3(new Web3.providers.HttpProvider(rpcUrl));

    const privateKey = 'YOUR_PRIVATE_KEY';
    const signer = new ethers.Wallet(privateKey, web3);

    const moonshot = new Moonshot({
        signer: signer,
        env: Environment.Testnet,
    });

    try {
        const token = await Token.create({
            tokenAddress: '0xF6089b8DB683C13dE522A275BF6F71E52FB01EC6',
            moonshot,
        });
        console.log('Token created successfully:', token);
    } catch (error) {
        console.error('Error creating token:', error);
    }
};

buyTx().catch(console.error);

This script throws an UNSUPPORTED_OPERATION error, as described in the logs above.
The Moonshot instance initializes without issues, but the error occurs during the token creation process. The rpcUrl and tokenAddress values are valid. Please review the script and let me know how to resolve this issue. If additional information is needed, I’m happy to provide it.

**Comment by bartoszl** [comment]
Hi seems like your issue might be related to the fact that you are passing a provider from `web3` library instead of `JsonRpcProvider` from `ethers`. 

These providers are not compatible and Typescript actually highlights this if you remove `@ts-nocheck`.

Try using:
```
import { JsonRpcProvider, Wallet } from 'ethers';

const rpcUrl = 'RPC_URL';

const provider = new JsonRpcProvider(rpcUrl);
const signer = new Wallet('private key', provider);
  ```
  
 Please see the following for more details: https://docs.moonshot.cc/developers/bot-sdk-base
 
 Closing the issue.

**Comment by shubhamanandspeqto** [comment]
I have tried it that way as well, but the same issue is still occurring.
i am sharing you screenshot 
![Screenshot from 2025-01-03 10-44-22](https://github.com/user-attachments/assets/250f8973-ff09-4cc3-8363-8f4063dbaae4)

**Comment by bartoszl** [comment]
Sorry I know what it is, you have to pass `provider` to `Token.create` function like so:

```
const token = await Token.create({
  tokenAddress: '0x022e17e694d831Ece83FF4DaFc61af2D4592260c',
  moonshot: moonshot,
  provider,
});
```
